language: python
python:
  - "2.7"
install:
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

before_script:
  - ansible --version
  - ansible-playbook --syntax-check ./tests/test.yml -i ./tests/hosts

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
