- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - cmake
    - python2

- name: get latest source from github
  git:
    dest: "{{ emscripten_path }}"
    repo: https://github.com/juj/emsdk.git
    force: true

- name: build
  shell: "{{ item }}"
  args:
    chdir: "{{ emscripten_path }}"
  with_items:
    - "./emsdk install  {{ emscripten_version }}"
    - "./emsdk activate {{ emscripten_version }}"
  environment:
    PATH: "{{ lookup('env', 'PATH') }}"
